#!/usr/bin/env bash -e

# Copyright (c) 2015, Georgios Gkitsas
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# 
# The views and conclusions contained in the software and documentation are those
# of the authors and should not be interpreted as representing official policies,
# either expressed or implied, of the FreeBSD Project.



#TODO:
# give option for the user to specify extraction directory
# on-demand install missing compression utils (eg 7zip)

# copied from https://gist.github.com/ggkitsas/857deb2cfbc44fae9dde
# written by Georgios Gkitsas

if [ "$1" = "upgrade" ]; then
    if [ `id -u` -ne 0 ]; then
        printf "You need root rights to upgrade. Try 'sudo decompress upgrade' or login as root user\n"
        exit 1;
    fi
    pushd /tmp/
    git clone https://gist.github.com/857deb2cfbc44fae9dde.git decompress
    pushd decompress
    mv decompress /usr/bin/
    popd
    rm -rf decompress
    exit 0;
elif [[ ("$1" = "help") || ($# -eq 0) ]]; then
    printf "Usage:"
    printf "\n\t%-40s%-40s" "To decompress an archive:" "decompress <filename>"
    printf "\n\t%-40s%-40s"   "To upgrade the decompress utility:" "decompress upgrade"
    printf "\n\t%-40s%-40s\n" "To present the help message:" "decompress help"
    exit 0;
fi

basename=$(basename "$1")
ext="${basename##*.}"
filename="${basename%.*}"
dir=$(dirname "$1")
ext2="${filename##*.}"

case $ext in
    zip)
        echo "zip"
        unzip "$1" -d $dir
    ;;
    bz2)
        if [ $ext2 = "tar" ]
        then
            echo "tar.bz2"
            tar -jxf "$1" --directory $dir
        else
            echo "bz2"
            bzip2 -d "$1"
        fi
    ;;
    gz)
        if [ $ext2 = "tar" ]
        then
            echo "tar.gz"
            tar -zxvf "$1" --directory $dir
        else
            echo "gz"
            gzip -d "$1"
        fi
    ;;
    tgz)
        echo "tgz"
        tar -zxvf "$1" --directory $dir
    ;;
    tbz2)
        echo "tbz2"
        tar -jxvf "$1" --directory $dir
    ;;
    xz)
        if [ $ext2 = "tar" ]
        then
            echo "tar.xz"
            tar -xJf "$1" --directory $dir
        else
            echo "xz"
            xz -d "$1"
        fi
    ;;
    tar)
        echo "tar"
        tar -xvf "$1" --directory $dir
    ;;
    rar)
        echo "rar"
        unrar x "$1"
    ;;
    Z)
        echo "Z"
        uncompress "$1"
    ;;
    7z)
        echo "7z"
        7z x "$1"
    ;;
    *)
        echo "not supported file type"
        exit 2;
    ;;
esac
